mysql:
  image: groonga/mroonga:mysql5631_mroonga606
  ports:
    - '3306:3306'
  volumes_from:
    - datastore

memcache:
  image: memcached:1.4.26
  ports:
    - '11211:11211'
  volumes_from:
    - datastore

nginx:
  build: containers/nginx
  ports:
    - '80:80'
    - '443:443'
  volumes_from:
    - datastore
  links:
    - rails

datastore:
  build: containers/datastore
  volumes:
    - /Users/keizosuzuki/dev:/usr/src/app

rails:
  build: containers/rails
  ports:
    - '3000:3000'
  environment:
    RAILS_ENV: development
    DATABASE_URL: mysql2://root@mysql:3306
    MEMCACHE_URL: memcache:11211
    ELASTICSEARCH_URL: http://elasticsearch:9200
    SECRET_KEY_BASE: hogehoge
  volumes_from:
    - datastore
  links:
    - mysql
    - memcache
    - elasticsearch

elasticsearch:
  build: containers/elasticsearch
  ports:
    - '9200:9200'
    - '9300:9300'
  volumes_from:
    - datastore
